# Generated by Django 5.2.5 on 2025-08-29 11:20

import datetime

import recurrence.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether bookings require manual confirmation.",
                        verbose_name="Require confirmation",
                    ),
                ),
                (
                    "allows_waitlist",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to join a waitlist if the event is full.",
                        verbose_name="Allow waitlists",
                    ),
                ),
                (
                    "recurrence_rule",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text="Recurrence rule in iCalendar `RFC 5545` format.",
                        null=True,
                        verbose_name="Recurrence rule",
                    ),
                ),
                (
                    "buffer_before",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(0),
                        help_text="Time buffer before the event starts (e.g., for setup).",
                        null=True,
                        verbose_name="Buffer time before event",
                    ),
                ),
                (
                    "buffer_after",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=300),
                        help_text="Time buffer after the event ends (e.g., for cleanup).",
                        null=True,
                        verbose_name="Buffer time after event",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of participants allowed for the event.",
                        verbose_name="Maximum capacity",
                    ),
                ),
                (
                    "booking_policy",
                    models.CharField(
                        choices=[
                            ("F", "Free"),
                            ("D", "Deposit required"),
                            ("P", "Paid in full"),
                            ("C", "Paid on credit"),
                        ],
                        default="F",
                        help_text="Policy for booking this event: Free, Deposit required, or Paid in full.",
                        max_length=1,
                        verbose_name="Booking policy",
                    ),
                ),
                (
                    "deposit",
                    models.FloatField(
                        blank=True,
                        help_text="The deposit amount required to reserve a spot for this event, if applicable.",
                        null=True,
                        verbose_name="Deposit amount",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        help_text="The price for the event, if applicable.",
                        null=True,
                        verbose_name="Event price",
                    ),
                ),
                (
                    "refundable",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether payments (such as deposits or fees) are refundable if the booking is cancelled.",
                        verbose_name="Refundable",
                    ),
                ),
                (
                    "refundable_before",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time before which a refund is allowed if the booking is cancelled.",
                        null=True,
                        verbose_name="Refundable before",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("P", "Public access"),
                            ("R", "Restricted access"),
                            ("I", "Invite only"),
                        ],
                        default="P",
                        help_text="Access level required to join the event: Public, Restricted, or Invite only.",
                        max_length=1,
                        verbose_name="Access level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Check if the event should be visible and available for booking.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the descriptive name for this event.",
                        max_length=128,
                        verbose_name="Event name",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, prevents any further changes to this event.",
                        verbose_name="Is locked",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        help_text="Specify the date and time when the event will begin.",
                        verbose_name="Event start date and time",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        help_text="Specify the date and time when the event will end.",
                        verbose_name="Event end date and time",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether bookings require manual confirmation.",
                        verbose_name="Require confirmation",
                    ),
                ),
                (
                    "allows_waitlist",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to join a waitlist if the event is full.",
                        verbose_name="Allow waitlists",
                    ),
                ),
                (
                    "recurrence_rule",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text="Recurrence rule in iCalendar `RFC 5545` format.",
                        null=True,
                        verbose_name="Recurrence rule",
                    ),
                ),
                (
                    "buffer_before",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(0),
                        help_text="Time buffer before the event starts (e.g., for setup).",
                        null=True,
                        verbose_name="Buffer time before event",
                    ),
                ),
                (
                    "buffer_after",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=300),
                        help_text="Time buffer after the event ends (e.g., for cleanup).",
                        null=True,
                        verbose_name="Buffer time after event",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of participants allowed for the event.",
                        verbose_name="Maximum capacity",
                    ),
                ),
                (
                    "booking_policy",
                    models.CharField(
                        choices=[
                            ("F", "Free"),
                            ("D", "Deposit required"),
                            ("P", "Paid in full"),
                            ("C", "Paid on credit"),
                        ],
                        default="F",
                        help_text="Policy for booking this event: Free, Deposit required, or Paid in full.",
                        max_length=1,
                        verbose_name="Booking policy",
                    ),
                ),
                (
                    "deposit",
                    models.FloatField(
                        blank=True,
                        help_text="The deposit amount required to reserve a spot for this event, if applicable.",
                        null=True,
                        verbose_name="Deposit amount",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        help_text="The price for the event, if applicable.",
                        null=True,
                        verbose_name="Event price",
                    ),
                ),
                (
                    "refundable",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether payments (such as deposits or fees) are refundable if the booking is cancelled.",
                        verbose_name="Refundable",
                    ),
                ),
                (
                    "refundable_before",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time before which a refund is allowed if the booking is cancelled.",
                        null=True,
                        verbose_name="Refundable before",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("P", "Public access"),
                            ("R", "Restricted access"),
                            ("I", "Invite only"),
                        ],
                        default="P",
                        help_text="Access level required to join the event: Public, Restricted, or Invite only.",
                        max_length=1,
                        verbose_name="Access level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Check if the event should be visible and available for booking.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the event type.",
                        max_length=128,
                        verbose_name="Event type name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_rule",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text="Recurrence rule in iCalendar `RFC 5545` format.",
                        null=True,
                        verbose_name="Recurrence rule",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="availabilities",
                        related_query_name="availability",
                        to="django_timely.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "assets",
                    models.ManyToManyField(
                        related_name="asset_groups", to="django_timely.asset"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="django_timely.assettype",
            ),
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attendee", "Attendee"),
                            ("instructor", "Instructor"),
                            ("presenter", "Presenter"),
                            ("facilitator", "Facilitator"),
                            ("assistant", "Assistant"),
                        ],
                        default="attendee",
                        help_text="The role of this participant in the event",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="invited",
                        help_text="The current status of this participant",
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="django_timely.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipantAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="django_timely.asset",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="django_timely.eventparticipant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="assets",
            field=models.ManyToManyField(
                through="django_timely.EventParticipantAsset", to="django_timely.asset"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the type or category that best describes this event.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="events",
                related_query_name="event",
                to="django_timely.eventtype",
                verbose_name="Event type",
            ),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fixed assets located at this venue",
                        to="django_timely.asset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the venue where this event will take place.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="django_timely.venue",
            ),
        ),
        migrations.CreateModel(
            name="VenueAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_rule",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text="Recurrence rule in iCalendar `RFC 5545` format.",
                        null=True,
                        verbose_name="Recurrence rule",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="availabilities",
                        related_query_name="availability",
                        to="django_timely.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="eventparticipantasset",
            constraint=models.UniqueConstraint(
                fields=("participant", "asset"), name="unique_participant_asset"
            ),
        ),
    ]
